import "./style/style.css"
import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap/dist/js/bootstrap.min.js"
import "bootstrap"
import "./components/navbar.js"
import "./components/footer.js"
import "./API/get-list.js"
import "./API/get-detail.js"
